version: "3.3"

services:
  alpine:
    build:
      context: .
      dockerfile: alpine_dockerfile
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  ubuntu:
    build:
      context: .
      dockerfile: ubuntu_dockerfile
    command: "python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"